"""update chunks table schema

Revision ID: 47dfe4b1101b
Revises: 524e21755e01
Create Date: 2026-07-22 18:48:47.213888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dfe4b1101b'
down_revision: Union[str, None] = '524e21755e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('token_count', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('doc_char_start', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('doc_char_end', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('chunking_method', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('bbox_union', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('section_path', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('block_types', sa.Text(), nullable=True))
    op.add_column('chunks', sa.Column('prev_chunk_id', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('next_chunk_id', sa.String(), nullable=True))
    op.alter_column('chunks', 'embedding_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chunks', 'page')
    op.drop_column('chunks', 'char_end')
    op.drop_column('chunks', 'text_preview')
    op.drop_column('chunks', 'char_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('char_start', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('text_preview', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('char_end', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('chunks', 'embedding_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chunks', 'next_chunk_id')
    op.drop_column('chunks', 'prev_chunk_id')
    op.drop_column('chunks', 'block_types')
    op.drop_column('chunks', 'section_path')
    op.drop_column('chunks', 'bbox_union')
    op.drop_column('chunks', 'content_hash')
    op.drop_column('chunks', 'chunking_method')
    op.drop_column('chunks', 'page_end')
    op.drop_column('chunks', 'page_start')
    op.drop_column('chunks', 'doc_char_end')
    op.drop_column('chunks', 'doc_char_start')
    op.drop_column('chunks', 'token_count')
    op.drop_column('chunks', 'text')
    # ### end Alembic commands ###
